### ISSUE TITLE
Use 2 menus for columns of links in default variant

### ISSUE THREAD

**Issue by genjohnson** [uiowa/uiowa_footer#3]
Similar to the work that was done in https://github.com/uiowa/rusty/tree/uiowa_footer_two_menus, adjust the default variant to use separate menus for the two columns of links. This will allow content contributors to have full control over the order and number of links in each column, which is important for sites which have different topics/groupings of links in each column (e.g., internal departments vs. commonly-visited pages)

**Comment by joewhitsitt** [comment]
in rusty, i just realized webmaster didn't have permissions for the social and footer menus that exist already. these are managed in the user.role.webmaster.yml config file. it might make sense then to make the footer secondary menu part of rusty to avoid having to set permissions for uiowa_footer.
