### ISSUE TITLE
Remove menus

### ISSUE THREAD

**Issue by genjohnson** [uiowa/uiowa_footer#5]
Now that we're providing the Social Media and Footer Second menus (and using the default Footer menu) and setting those as the defaults in the uiowa_footer configuration, I'm not convinced that it makes sense to continue providing fields for this configuration out of the box (also note that these fields are currently configured to be disabled out of the box).

I propose that we continue to specify these menus as the default configuration but remove the fields from the configuration form. In the case that a site needs to expose a selection field to content contributors to select different menus, that can still be accomplished by using hook_form_alter() and a custom submit handler to save the config values (similar to what is being done in uiowa_footer now).

**Comment by joewhitsitt** [comment]
My only argument against this is to provide the user with context about what menus are being used in the footer and where they need to go to add links to it. The tour highlights this and has links to send them to social/footer menus (could be improved). Help text could have the links as well to aid users in jumping around.

**Comment by genjohnson** [comment]
So after more discussion about the possibility of using multiple install profiles, it seems like a different approach should be taken to have better separation of configuration between this module and install profiles/individual websites.

Proposed changes:

- The uiowa_footer module will not provide any menus. It will be up to the profile or specific site to provide the menus to be used.
- The uiowa_footer module will not specify any menus to be used in its config file, since the module will not be providing any menus and we do not want to make assumptions about which menus may be available on a per-site basis.
- The menu selection fields will be made available (and not disabled) out of the box, and install profiles or specific sites may provide their own form overrides to disable/hide the fields and optionally display help text about which menus are being used.

**Comment by pyrello** [comment]
Those changes sound good to me @genjohnson.

**Comment by genjohnson** [comment]
@pyrello thanks for the feedback! 

Just for the record, @joewhitsitt also agreed in Slack. 

I'm going to move forward with these changes.
